# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studfacstatus',
            old_name='approved',
            new_name='approval',
        ),
        migrations.RenameField(
            model_name='studlabstatus',
            old_name='approved',
            new_name='approval',
        ),
    ]
