# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161114_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'OnlineCC', max_length=250)),
                ('webmail', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Submit Thesis', max_length=250)),
                ('webmail', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='CC_approval',
            new_name='assistant_registrar_approval',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='HOD_approval',
            new_name='cc_approval',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='asstreg_approval',
            new_name='hod_approval',
        ),
        migrations.AddField(
            model_name='student',
            name='online_cc_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='submit_thesis',
            field=models.BooleanField(default=False),
        ),
    ]
